// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZZPzPtoZ9zFQ_xj8YOoD0TWe3MusF1Ic',
    appId: '1:723644315316:web:be0075f091c0d345f1c9e1',
    messagingSenderId: '723644315316',
    projectId: 'roadaware-4c8ca',
    authDomain: 'roadaware-4c8ca.firebaseapp.com',
    storageBucket: 'roadaware-4c8ca.firebasestorage.app',
    measurementId: 'G-V2LB274LWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY-1H8VkZWRxVF03U91vbODh1Ewn6MBRk',
    appId: '1:723644315316:android:a629f438ea5407def1c9e1',
    messagingSenderId: '723644315316',
    projectId: 'roadaware-4c8ca',
    storageBucket: 'roadaware-4c8ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUiT5BzgRyWjGs_5YVyxTxYZkCsthFIGg',
    appId: '1:723644315316:ios:0e731a0b7bbfb03df1c9e1',
    messagingSenderId: '723644315316',
    projectId: 'roadaware-4c8ca',
    storageBucket: 'roadaware-4c8ca.firebasestorage.app',
    iosBundleId: 'com.roadaware.app.roadAwareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUiT5BzgRyWjGs_5YVyxTxYZkCsthFIGg',
    appId: '1:723644315316:ios:0e731a0b7bbfb03df1c9e1',
    messagingSenderId: '723644315316',
    projectId: 'roadaware-4c8ca',
    storageBucket: 'roadaware-4c8ca.firebasestorage.app',
    iosBundleId: 'com.roadaware.app.roadAwareApp',
  );
}
